# config/packages/knp_gaufrette.yaml
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        bookPictures:
            local:
                directory: '%kernel.project_dir%/public/allPictures' 
# config/packages/knp_gaufrette.yaml
    filesystems:
        bookPictures:
            adapter:    bookPictures
            alias:      bookPictures_filesystem