# config/packages/knp_gaufrette.yaml
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        allPictures:
            local:
                directory: '%kernel.project_dir%/public/allPictures' 
# config/packages/knp_gaufrette.yaml
    filesystems:
        allPictures:
            adapter:    allPictures
            alias:      allPictures_filesystem