twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # category: 'category'
        # categories: 'categories'
        # authors: 'authors'
        # collections: 'collections'
        # books: 'books'
        # book: 'book'
        

    paths:
        '%kernel.project_dir%/assets/styles' : styles

when@test:
    twig:
        strict_variables: true
    
