twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        categories: '@App\Twig\CategoriesExtension'
        authors: 'authors'
        author: 'author'
        collections: 'collections'
        books: 'books'
        book: 'book'

    paths:
        '%kernel.project_dir%/assets/styles' : styles

when@test:
    twig:
        strict_variables: true
    
