vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute
        
    # storage: gaufrette

    mappings:
            authors:
                uri_prefix: /allPictures/authors
                upload_destination: '%kernel.project_dir%/public/ allPictures/authors'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            bookImages:
                uri_prefix: /allPictures/bookPictures
                upload_destination: '%kernel.project_dir%/public/allPictures/bookImages'
                namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'

            collections:
                uri_prefix: /allPictures/collectionImages
                upload_destination: '%kernel.project_dir%/public/allPictures/collectionImages'
                namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'

            bookReads:
                uri_prefix: /bookReads
                upload_destination: '%kernel.project_dir%/public/bookReads'
                namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
                
                inject_on_load: false
                delete_on_update: true
                delete_on_remove: true