vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
        authors:
            uri_prefix: /allPictures/authors
            upload_destination: '%kernel.project_dir%/public/allPictures/authors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        bookImages:
            uri_prefix: /allPictures/bookPictures
            upload_destination: '%kernel.project_dir%/public/allPictures/bookPictures'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'

        allBooks:
            uri_prefix: /allPictures/allBooks
            upload_destination: '%kernel.project_dir%/public/allPictures/allBooks'
            namer: 'Vich\UploaderBundle\Naming\SmartUniqueNamer'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true